CREATE TABLE application_review_records (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, draft_id TEXT NOT NULL REFERENCES application_drafts(id) ON DELETE CASCADE, draft_version INTEGER NOT NULL, payload_hash TEXT NOT NULL, findings_json TEXT NOT NULL CHECK(json_valid(findings_json)), status TEXT NOT NULL CHECK(status IN ('active','invalidated')), created_at TEXT NOT NULL, invalidated_at TEXT, UNIQUE(draft_id,draft_version,payload_hash)) STRICT;
CREATE TABLE application_confirmation_records (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, draft_id TEXT NOT NULL REFERENCES application_drafts(id) ON DELETE CASCADE, review_id TEXT NOT NULL REFERENCES application_review_records(id) ON DELETE CASCADE, payload_hash TEXT NOT NULL, confirmation_hash TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('active','consumed','invalidated')), expires_at TEXT NOT NULL, created_at TEXT NOT NULL, consumed_at TEXT, UNIQUE(id, owner_id, draft_id, review_id), FOREIGN KEY(draft_id, owner_id) REFERENCES application_drafts(id, owner_id) ON DELETE CASCADE) STRICT;
CREATE TABLE application_submission_receipts (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, draft_id TEXT NOT NULL REFERENCES application_drafts(id) ON DELETE RESTRICT, review_id TEXT NOT NULL REFERENCES application_review_records(id) ON DELETE RESTRICT, confirmation_id TEXT NOT NULL REFERENCES application_confirmation_records(id) ON DELETE RESTRICT, idempotency_key TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('submitted','handed_off')), external_url TEXT, created_at TEXT NOT NULL, UNIQUE(owner_id,draft_id,idempotency_key), UNIQUE(confirmation_id)) STRICT;
CREATE TABLE application_delegation_records (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, agent_id TEXT NOT NULL, resource_type TEXT NOT NULL CHECK(resource_type='application_draft'), resource_id TEXT NOT NULL REFERENCES application_drafts(id) ON DELETE CASCADE, operations_json TEXT NOT NULL CHECK(json_valid(operations_json)), purpose TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('requested','active','revoked')), expires_at TEXT NOT NULL, created_at TEXT NOT NULL, approved_at TEXT, revoked_at TEXT) STRICT;
CREATE TABLE application_data_grant_records (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, recipient_id TEXT NOT NULL, purpose TEXT NOT NULL, payload_hash TEXT NOT NULL, fields_json TEXT NOT NULL CHECK(json_valid(fields_json)), status TEXT NOT NULL CHECK(status IN ('requested','active','withdrawn')), expires_at TEXT NOT NULL, created_at TEXT NOT NULL, approved_at TEXT, withdrawn_at TEXT) STRICT;
CREATE TRIGGER application_review_records_bind_owner BEFORE INSERT ON application_review_records WHEN NOT EXISTS (SELECT 1 FROM application_drafts WHERE id=NEW.draft_id AND owner_id=NEW.owner_id) BEGIN SELECT RAISE(ABORT,'review owner must own draft'); END;
CREATE TRIGGER application_confirmation_records_bind_payload BEFORE INSERT ON application_confirmation_records WHEN NOT EXISTS (SELECT 1 FROM application_review_records WHERE id=NEW.review_id AND owner_id=NEW.owner_id AND draft_id=NEW.draft_id AND payload_hash=NEW.payload_hash AND status='active') BEGIN SELECT RAISE(ABORT,'confirmation must bind active review payload'); END;
CREATE TRIGGER application_receipts_bind_consumed_confirmation BEFORE INSERT ON application_submission_receipts WHEN NOT EXISTS (SELECT 1 FROM application_confirmation_records WHERE id=NEW.confirmation_id AND owner_id=NEW.owner_id AND draft_id=NEW.draft_id AND review_id=NEW.review_id AND status='consumed') BEGIN SELECT RAISE(ABORT,'receipt must bind consumed owner confirmation'); END;
CREATE TRIGGER application_delegation_records_bind_owner BEFORE INSERT ON application_delegation_records WHEN NOT EXISTS (SELECT 1 FROM application_drafts WHERE id=NEW.resource_id AND owner_id=NEW.owner_id) BEGIN SELECT RAISE(ABORT,'delegation owner must own draft'); END;
